//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ConfirmEmailRequest defines model for ConfirmEmailRequest.
type ConfirmEmailRequest struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

// ConfirmEmailResponse defines model for ConfirmEmailResponse.
type ConfirmEmailResponse struct {
	// RefreshToken Refresh token
	RefreshToken string `json:"refresh_token"`

	// Token JWT token
	Token string `json:"token"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// RefreshToken Refresh token
	RefreshToken string `json:"refresh_token"`

	// Token JWT token
	Token string `json:"token"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	// RefreshToken Refresh token
	RefreshToken string `json:"refresh_token"`

	// Token JWT token
	Token string `json:"token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	Message string `json:"message"`
}

// Token defines model for Token.
type Token struct {
	// Token JWT token
	Token string `json:"token"`
}

// ChatMultipartBody defines parameters for Chat.
type ChatMultipartBody struct {
	Audio *openapi_types.File `json:"audio,omitempty"`
}

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = ConfirmEmailRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ChatMultipartRequestBody defines body for Chat for multipart/form-data ContentType.
type ChatMultipartRequestBody ChatMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Confirm user email address
	// (POST /api/auth/confirm-email)
	ConfirmEmail(w http.ResponseWriter, r *http.Request)
	// Login to get a JWT token
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out current user
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh access and refresh tokens
	// (POST /api/auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /api/auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Validate current authentication token
	// (GET /api/auth/validate-token)
	ValidateToken(w http.ResponseWriter, r *http.Request)
	// Chat with voice assistant (send audio, get text)
	// (POST /api/chat)
	Chat(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ConfirmEmail operation middleware
func (siw *ServerInterfaceWrapper) ConfirmEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateToken operation middleware
func (siw *ServerInterfaceWrapper) ValidateToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Chat operation middleware
func (siw *ServerInterfaceWrapper) Chat(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Chat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/confirm-email", wrapper.ConfirmEmail)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.Logout)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/refresh", wrapper.RefreshTokens)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/register", wrapper.Register)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/validate-token", wrapper.ValidateToken)
	m.HandleFunc("POST "+options.BaseURL+"/api/chat", wrapper.Chat)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYQW/jNhP9KwN+36EFFDtptxffsostkKKHYDe7PQRBwYgjixuJ1A4pJ+7C/70YUrIj",
	"W3KcNraD7SmxOCSHb96bGfKbSG1ZWYPGOzH5JlyaYynDv++syTSV70upiw/4tUbn+XNFtkLyGoNRahXy",
	"Xz+vUEyE86TNVCwSgTytZ2SRCMKvtSZUYnLdmCVxnZuktba3XzD1vE7XC1dZ43DTDcKM0OV/enuHhj8o",
	"dCnpymtrxER8iMMQh5NNbwfm/fbH1dCctXO0Vl1H+g70nsjS5glKdE5O8WnEWsO+tX+3U20GYzUUkkRU",
	"0rl7S2r3eC1nbHHjOwhW48sgpBtH2b7xMzb8LsCbaueRjk/IlSdDsD6SHz7IsiowgMnTSDJG4Oo0Reey",
	"uhjBZYHSIaQ5pncwtzVBcAO8hRmSzubxo0xTWxs/ehLTbZq+agPWdfiF4ri54yIRDtOatJ9/5GIQt3uL",
	"kpDOa5/zr9vw61dLpfRxU5HE0sErxdGVA7n3lVjwwtpkdtPn88sLyCzBzOoUQTqnnZfGw61M79AoXkj7",
	"EJDPweJ8aXF+eSESMUNycaWz0enolEGzFRpZaTERP4dPzA+fh5OMZaXHsvb5OI2l5WRJw8pGljLOIegX",
	"Skw6FUhEDNH5t1bNYwE0Hk2YJquq0GmYOP7irFnVU/7v/4SZmIj/jVcFd9xU23FfqV10A+apxvAhMjgc",
	"5afT0z250Mgk+NANVjCABjpUj2RRzBn5Ny/oUyyVPU5cmJkstAJqseJ93+x/308OKVDV5wgV2ZlWqKL2",
	"x9zBgLEeMlsbxS79chgoPJKRBTikGRJgY5gIV5elpPmKwVCz+zFTSaUInWNtyanjfMDaRuMb98QNL7HS",
	"SsElfVgjoeLvSRydpubAquh2Mj3wB4NHIjiuBM4Ot29KqJgusnCviusxIN7CFD1I6NTDXZlua7+V6jz+",
	"L0m3Q/fx8VFmhcJOp6gg7rxZ2NdreB9Pbe03iHoAwnwyDKsl/ReqEbT0sQSldk6bKchOOJpoHZVSoGpG",
	"FiIVONEzaJ3WSEyuu03R9c3iZo2HHC1IayI0PuTenTnY9NbDJGza/NAbuj3l3bW7z4Ez7/pFqCd28fTQ",
	"gPWqepGD6+oqxxaIqCDQDnR07fWKaamW9toqQwBBGtU9jXuGdOJVb5t2Got9yaZ7691JN2d72H5YOEP3",
	"2mNphqtB6E1lQSjVHPBBO/+6+ooWV5Bg8P556TwcVno8WV7ap9hDzM+N2dXyhWW/DcZVmyeCf6N/1lis",
	"L3LUtiIBfKhYZ8nTDcZzinkbmWU1711yBzqkudzSWr7j0W1ZqawLrytJfpxZKk+U9HJb1GWtdHhvydqX",
	"mltt+EQ7Rvplq/3a+xU++P7XvScp16Y2yMiW669G/6m6/zwWM73gXvt846XtB4dGQaBLEi5OHJ0feffF",
	"3wEAAP//5ndm8yEaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
