version: "3.8"

networks:
  voice_assistant_network:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assistant
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voice_assistant_network

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - voice_assistant_network

  backend:
    image: hlofiys/voice-assistant-backend:main
    depends_on:
      - postgres
      - chromadb
    environment:
      DB_DRIVER: postgres
      DB_SOURCE: postgresql://postgres:postgres@postgres:5432/assistant?sslmode=disable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assistant
      SERVER_ADDRESS: 0.0.0.0:8080
      CHROMA_BASE_URL: http://chromadb:8000
      CHROMA_COLLECTION_NAME: chatbot-pharmacies
      GOOGLE_EMBEDDING_MODEL_NAME: text-embedding-004
      GOOGLE_CHAT_MODEL_NAME: gemini-2.0-flash-lite
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      
    ports:
      - "8082:8080"
    networks:
      - voice_assistant_network

volumes:
  postgres_data: