// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID       int32       `json:"id"`
	Text     string      `json:"text"`
	Location interface{} `json:"location"`
}

type User struct {
	UserID       pgtype.UUID      `json:"user_id"`
	Email        string           `json:"email"`
	Password     string           `json:"password"`
	Code         pgtype.Text      `json:"code"`
	RefreshToken pgtype.Text      `json:"refresh_token"`
	ExpiredAt    pgtype.Timestamp `json:"expired_at"`
}
