// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id,
    email,
    password,
    code
)VALUES(
    $1,$2,$3,$4
)
`

type CreateUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Code     pgtype.Text `json:"code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Code,
	)
	return err
}

const logoutById = `-- name: LogoutById :exec
UPDATE users
SET refresh_token = NULL, expired_at = NULL
WHERE user_id = $1
`

func (q *Queries) LogoutById(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, logoutById, userID)
	return err
}

const updateCodeById = `-- name: UpdateCodeById :one
UPDATE users
SET code = NULL, refresh_token = $3, expired_at = $4
WHERE email = $1 AND code = $2
RETURNING user_id
`

type UpdateCodeByIdParams struct {
	Email        string           `json:"email"`
	Code         pgtype.Text      `json:"code"`
	RefreshToken pgtype.Text      `json:"refresh_token"`
	ExpiredAt    pgtype.Timestamp `json:"expired_at"`
}

func (q *Queries) UpdateCodeById(ctx context.Context, arg UpdateCodeByIdParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateCodeById,
		arg.Email,
		arg.Code,
		arg.RefreshToken,
		arg.ExpiredAt,
	)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users
SET refresh_token = $1
WHERE user_id = $2
`

type UpdateRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.RefreshToken, arg.UserID)
	return err
}

const verifyRefreshToken = `-- name: VerifyRefreshToken :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE user_id = $1                               
      AND refresh_token = $2                         
      AND refresh_token IS NOT NULL                  
      AND expired_at IS NOT NULL                     
      AND $3 >= expired_at                           
      AND $3 <= expired_at + INTERVAL '1 month'      
)
`

type VerifyRefreshTokenParams struct {
	UserID       pgtype.UUID      `json:"user_id"`
	RefreshToken pgtype.Text      `json:"refresh_token"`
	ExpiredAt    pgtype.Timestamp `json:"expired_at"`
}

func (q *Queries) VerifyRefreshToken(ctx context.Context, arg VerifyRefreshTokenParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyRefreshToken, arg.UserID, arg.RefreshToken, arg.ExpiredAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
